version: '3'
services:
  backend: 
    build: ./backend
    ports:
      - 5000:5000
    container_name: backend-docker
    restart: always
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend-docker
    restart: always
    links: 
      - backend
    